smtCommunityLikeBox:
  caption:
    ja_JP: "コミュニティのいいね！"
    en_US: "Communities like!"
  description:
    ja_JP: "コミュニティのタイムラインにいいねを追加します。"
    en_US: "I want to add to the timeline of the community like."
  component: [like, smtLikeAll]
